default:
  image: ubuntu:20.04


workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always


variables:
  VAULT_ADDR: https://vault.oss.cloudp.libgbl.net
  VAULT_CACERT: ./certs/vault_ca.crt
  VAULT_ROLE: group_cloudp


before_script:
  - |
    echo "Performing pre-req setup"
    echo "...installing vault binary"
    apt update && apt install -y gpg apt-utils wget curl unzip > /dev/null 2>&1
    wget https://releases.hashicorp.com/vault/1.13.2/vault_1.13.2_linux_amd64.zip 2>/dev/null
    unzip vault_1.13.2_linux_amd64.zip >/dev/null 2>&1
    chmod +x vault
    mv vault /usr/local/bin


stages:
  - demo

vault_demo:
  stage: demo
  script:
    - |
      vault version
      echo "Getting vault token(vault auth using JWT token)"
      export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_ROLE} jwt=${CI_JOB_JWT})"
      echo "Got Vault token: ${VAULT_TOKEN}"
