
name: Testing on-prem vault integration

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: pre-reqs
      run: |
         echo "Performing pre-req setup"
         echo "...installing vault binary"
         apt update > /dev/null 2>&1
         apt install -y gpg apt-utils wget curl unzip > /dev/null 2>&1
         wget https://releases.hashicorp.com/vault/1.13.2/vault_1.13.2_linux_amd64.zip 2>/dev/null
         unzip vault_1.13.2_linux_amd64.zip >/dev/null 2>&1
         chmod +x vault
         mv vault /usr/local/bin

    - name: vault-demo
      env:
         VAULT_ADDR: https://vault.oss.cloudp.libgbl.net
         VAULT_CACERT: ./certs/vault_ca.crt
         VAULT_ROLE: group_cloudp
         VAULT_SECRET_PATH: /secrets/cloudp/init
         VAULT_SECRET_VALUE: my_secret
      run: |
         vault version
         echo "Getting vault token(vault auth using JWT token)"
         export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_ROLE} jwt=${CI_JOB_JWT})"
         [ $? -eq 0 ] && echo "Vault token fetch: SUCCESS!"
         echo "Fetching secret from vault path: ${VAULT_SECRET_PATH}"
         export SECRET="$(vault kv get -field=${VAULT_SECRET_VALUE} ${VAULT_SECRET_PATH})"
         echo "Got Secret: ${SECRET}"
